### ISSUE TITLE
v0.1.5 から v0.2.0 への移行が上手くいかない

### ISSUE THREAD

**Issue by KusaReMKN** [sasakulab/misskey-now#26]
どうやら 6 行目から始まる `then` のコールバック関数が上手く仕事をしていないようです

**Comment by sasakulari** [comment]
もう全部書き直そうと思いました。

**Comment by KusaReMKN** [comment]
例えば、移行する必要があるか否かを先に判別してしまって、移行する必要があるなら `chrome.storage.local` に値を詰めてしまいます（移行専用処理）。 その後に初期化用の処理を走らせれば、初期化処理は常に最新版のデータ構造のみを相手にすればよくなりそうですね。

移行用の処理は分岐の修正でなんとかなりそうな気もします。 がんばれくらりちゃん

**Comment by sasakulari** [comment]
## 謝辞
何から何までありがとう　本当に

## 変数の状態（有無）
|変数の有無|初回起動|v0.1.5|v0.2.0|
|----|----|----|----|
|version|No|No|Yes|
|instance|No|Yes|No|
|key|No|Yes|No|
|profiles|No|No|Yes|

**Comment by KusaReMKN** [comment]
↓ で移行できそう
```clike
if (version === 0.2.0) {
  移行済み;
  なにもしない
} else if (instance === undef && key === undef) {
  初回起動;
  空データ詰め込み;
} else {
  移行処理;
  profiles['hogehoge'] = { instance, key };
}
```

**Comment by sasakulari** [comment]
なるほど、okay です。undef はよしなにすればいいんですねー

**私が** 直感的にわかりやすいので、`typeof` 演算子を利用してチェックをかけることにします。
変数が未定義の場合 `typeof hoge === 'undefined'` -> `True` が立ちます。
移行の必要性は、これで判断することにします。

```
if (version === 0.2.0) {
  // 移行済み;
  // なにもしない
} else if (typeof instance === 'undefined'  && typeof key === 'undefined') {
  // 初回起動;
  // 空データ詰め込み;
} else {
  // 移行処理;
  // profiles['hogehoge'] = { instance, key };
}
```

**Comment by sasakulari** [comment]
メモ、登録されているすべての変数を表示
```
chrome.storage.local.get(null, ((data) => {console.log(data)}));
```

**Comment by sasakulari** [comment]
多分うまくいったような気がする

**Comment by KusaReMKN** [comment]
6f5a89be のコミットの main.js の 45 行目の settings、きっと 40 行目の左辺値を取りたいんだろうけどスコープが違うから見えてない

https://mi.yude.moe/notes/9b4kdo273k
