### ISSUE TITLE
多重送信できないようにする

### ISSUE THREAD

**Issue by KusaReMKN** [sasakulab/misskey-now#29]
Misskey Now! のボタンを間違ってダブルクリックすると連投されてしまうようです。
投稿に成功したら一定時間ボタンを無効にする機能で対応できそうな気がします。

**Comment by KusaReMKN** [comment]
これ、成功したらでは駄目で、

- 押されると同時に無効化
- 成功失敗の解決を待る
- 成功だったら一定時間後に有効化、
- 失敗だったら即座に有効化

とかのほうが良さそうですね

**Comment by sasakulari** [comment]
ダブルクリックしたことなかった
たしかに

**Comment by KusaReMKN** [comment]
今週のどこかでやります

**Comment by sasakulari** [comment]
やったぁ

**Comment by KusaReMKN** [comment]
投稿して Success になったらボタンを完全に無効化しても良いですか？
つまり、一旦投稿したらポップアップを閉じるまで再投稿できなくなります

**Comment by sasakulari** [comment]
複数プロファイルに対応しているので、２つ以上のアカウントで同じサイトを投げたい需要があるかもしれないと思いました。

ポップアップを開き直せばいいといえばそのとおりですが、その辺りの UX は @KusaReMKN さんはどう思いますか？

**Comment by KusaReMKN** [comment]
> ２つ以上のアカウントで同じサイトを投げたい需要があるかもしれない
たしかにその通りかもしれませんね
同じ内容を毎度入力するのは面倒なので何回でも押せるようにしてみます
