### ISSUE TITLE
POST すると `405` エラーが返ってくる

### ISSUE THREAD

**Issue by sasakulari** [sasakulab/misskey-now#3]
XMLHttpRequest 派だったので、 fetch に対する知識がまったくない

なぜ fetch を使ったかと言うと、拡張機能 (v3) で CORS を回避するために簡単な手段が fetch にしか対応していなかったから

**Comment by KusaReMKN** [comment]
多分 method の値は大文字で指定してやる必要があるんだと思う 知らんけど

**Comment by sasakulari** [comment]
マジかよ

**Comment by sasakulari** [comment]
![image](https://user-images.githubusercontent.com/58127312/216818767-edc4821a-fb3a-4944-b108-71fad92d4cd8.png)
私は私のエラーを読んでいなかったことを深く恥じました。

また今度直そう

**Comment by sasakulari** [comment]
closed
